//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGLUONG
    {
        public int ID { get; set; }
        public string MAKYCONG { get; set; }
        public Nullable<int> MANV { get; set; }
        public string HOTEN { get; set; }
        public Nullable<double> NGAYCONGTRONGTHANG { get; set; }
        public Nullable<double> LUONGNGAYPHEP { get; set; }
        public Nullable<double> LUONGNGAYKHONGPHEP { get; set; }
        public Nullable<double> LUONGNGAYLE { get; set; }
        public Nullable<double> LUONGNGAYCHUNHAT { get; set; }
        public Nullable<double> UNGLUONG { get; set; }
        public Nullable<double> PHUCAP { get; set; }
        public Nullable<double> LUONGTANGCA { get; set; }
        public Nullable<double> SOTIENKYLUAT { get; set; }
        public Nullable<double> SOTIENKHENTHUONG { get; set; }
        public Nullable<double> LUONGNGAYTHUONG { get; set; }
        public Nullable<double> LUONGTHUCLANH { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
    }
}
