//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_BANGCONG
    {
        public int MABC { get; set; }
        public int NAM { get; set; }
        public int THANG { get; set; }
        public int NGAY { get; set; }
        public int GIOVAO { get; set; }
        public int PHUTVAO { get; set; }
        public int GIORA { get; set; }
        public int PHUTRA { get; set; }
        public int MANV { get; set; }
        public int IDLC { get; set; }
        public Nullable<int> IDLOAICONG { get; set; }
    
        public virtual tb_LOAICONG tb_LOAICONG { get; set; }
    }
}
