//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN_PHUCAP
    {
        public int ID { get; set; }
        public int MANV { get; set; }
        public int IDPC { get; set; }
        public string NGAY { get; set; }
        public string NOIDUNG { get; set; }
        public double SOTIEN { get; set; }
    }
}
