//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TANGCA
    {
        public int ID { get; set; }
        public int NAM { get; set; }
        public int THANG { get; set; }
        public int NGAYTANGCA { get; set; }
        public double SOGIO { get; set; }
        public int MANV { get; set; }
        public int IDLOAICA { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<double> HESOTANGCA { get; set; }
        public Nullable<double> SOTIEN { get; set; }
        public Nullable<System.DateTime> DATE_TANGCA { get; set; }
    
        public virtual tb_LOAICA tb_LOAICA { get; set; }
    }
}
