//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_USER
    {
        public int ID { get; set; }
        public Nullable<int> MANV_LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string HASHPASSWORD { get; set; }
        public Nullable<int> ROLE { get; set; }
    }
}
