//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_CHUYENNHANVIEN
    {
        public int ID { get; set; }
        public string SOQUYETDINH { get; set; }
        public int MANV { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> IDPBHIENTAI { get; set; }
        public Nullable<int> IDPHONGBANMOI { get; set; }
        public string LYDO { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<System.DateTime> DELETE_DATE { get; set; }
    }
}
