//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KHENTHUONG_KYLUAT
    {
        public int ID { get; set; }
        public string SOQUYETDINH { get; set; }
        public string NOIDUNG { get; set; }
        public Nullable<System.DateTime> DENNGAY { get; set; }
        public int MANV { get; set; }
        public Nullable<int> LOAI { get; set; }
        public string LYDO { get; set; }
        public Nullable<System.DateTime> TUNGAY { get; set; }
        public Nullable<int> Status_tb { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<double> SOTIEN { get; set; }
    }
}
