//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_KYCONG
    {
        public int ID { get; set; }
        public string MAKYCONG { get; set; }
        public Nullable<int> THANG { get; set; }
        public Nullable<int> NAM { get; set; }
        public Nullable<int> KHOA { get; set; }
        public Nullable<System.DateTime> NGAYTINHCONG { get; set; }
        public Nullable<int> NGAYCONGTRONTHANG { get; set; }
        public Nullable<int> MACTY { get; set; }
        public Nullable<int> TRANGTHAI { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
    }
}
