//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NHANVIEN
    {
        public int ID { get; set; }
        public int MANV { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public System.DateTime NGAYSINH { get; set; }
        public string DIENTHOAI { get; set; }
        public string CCCD { get; set; }
        public string DIACHI { get; set; }
        public string IMGPATH { get; set; }
        public Nullable<int> IDPB { get; set; }
        public Nullable<int> IDBP { get; set; }
        public Nullable<int> IDCV { get; set; }
        public Nullable<int> IDTD { get; set; }
        public Nullable<int> IDDANTOC { get; set; }
        public Nullable<int> IDTONGIAO { get; set; }
        public Nullable<int> ROLE { get; set; }
        public Nullable<int> TrangThaiLamViec { get; set; }
    
        public virtual tb_BOPHAN tb_BOPHAN { get; set; }
        public virtual tb_CHUCVU tb_CHUCVU { get; set; }
        public virtual tb_PHONGBAN tb_PHONGBAN { get; set; }
        public virtual tb_TRINHDO tb_TRINHDO { get; set; }
    }
}
