//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_NANGLUONG
    {
        public int ID { get; set; }
        public string SOQUYETDINH { get; set; }
        public Nullable<int> MANV { get; set; }
        public Nullable<double> HSLUONGCU { get; set; }
        public Nullable<System.DateTime> NGAYKY { get; set; }
        public Nullable<double> HSLUONGMOI { get; set; }
        public string GHICHU { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<int> UPDATE_BY { get; set; }
        public string SOHOPDONG { get; set; }
        public Nullable<System.DateTime> NGAYLENLUONG { get; set; }
    }
}
